# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 05:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('emotion_id', models.AutoField(primary_key=True, serialize=False)),
                ('emotion_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('track_id', models.AutoField(primary_key=True, serialize=False)),
                ('emotion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Emotion')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('authorization_key', models.CharField(max_length=255)),
                ('access_token', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='track',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
    ]
