# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 05:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='track',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
