# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 06:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20161125_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='emotion',
            new_name='emotion_name',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='user',
            new_name='user_id',
        ),
    ]
