# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20161125_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_token',
            field=models.CharField(default='exit', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
