# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 01:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20161125_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='emotion_id',
        ),
        migrations.RemoveField(
            model_name='track',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Emotion',
        ),
        migrations.DeleteModel(
            name='Track',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
