# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 01:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0011_auto_20161128_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('emotion_id', models.AutoField(primary_key=True, serialize=False)),
                ('emotion_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('track_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(default=datetime.datetime.now)),
                ('end_time', models.DateTimeField(default=datetime.datetime.now)),
                ('emotion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='api.Emotion')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('authorization_key', models.CharField(max_length=255, unique=True)),
                ('access_token', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='track',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
    ]
